name: Lua lint and format

on:
  push:
    branches: [ "master" ]
    paths:
      - "lua/**"
  pull_request:
    branches: [ "master" ]
    paths:
      - "lua/**"

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Lua
        uses: lunarmodules/luacheck@v1
